-- ============================================================================
-- MARKETING MANAGEMENT SYSTEM - COMPLETE SUPABASE SCHEMA
-- ============================================================================
-- Covers all core modules: campaigns, customers, leads, opportunities,
-- budgets, promotions, influencers, content_items.
--
-- HOW TO RUN:
--   1. Open https://supabase.com/dashboard and select your project
--   2. Go to SQL Editor -> New query
--   3. Paste this entire file and click "Run"
--
-- NOTE ON RE-RUNNING:
--   Section 0 drops existing tables. Running the whole file RESETS your data.
--   If you only want to add missing tables without wiping anything, delete
--   Section 0 before running.
--
-- CONVENTIONS:
--   * All tables use TEXT ids ('C001', 'B001', ...) because the Flutter app
--     generates human-readable ids.
--   * Status/stage/source columns are plain TEXT on purpose - the app treats
--     them as free strings. Allowed values are documented per column.
-- ============================================================================


-- ============================================================================
-- 0. FULL RESET (optional - deletes all data!)
-- ============================================================================

drop table if exists public.content_items cascade;
drop table if exists public.influencers   cascade;
drop table if exists public.budgets       cascade;
drop table if exists public.promotions    cascade;
drop table if exists public.opportunities cascade;
drop table if exists public.leads         cascade;
drop table if exists public.customers     cascade;
drop table if exists public.campaigns     cascade;


-- ============================================================================
-- 1. CAMPAIGNS
-- ============================================================================
-- status      : Active | Draft | Paused | Completed | Cancelled
-- objective   : brandAwareness | leadGeneration | salesConversion |
--               customerRetention | productLaunch | eventPromotion
-- channels[]  : email | socialMedia | webPush | sms | influencer | search |
--               display
-- activities  : jsonb array of
--               { "description": str, "date": str,
--                 "iconCode": int?, "iconColorValue": int? }
-- coupons     : jsonb array of
--               { "code": str, "discount": str, "usageLimit": int,
--                 "usedCount": int, "expiryDate": str }

create table public.campaigns (
  id              text primary key,
  name            text not null,
  description     text not null default '',
  target_audience text not null default '',
  notes           text not null default '',
  objective       text not null default 'brandAwareness',
  channels        text[] not null default '{}',
  status          text not null default 'Draft',
  start_date      date,
  end_date        date,
  budget          numeric(14,2) not null default 0 check (budget >= 0),
  spent           numeric(14,2) not null default 0 check (spent >= 0),
  leads           integer not null default 0 check (leads >= 0),
  conversions     integer not null default 0 check (conversions >= 0),
  impressions     bigint not null default 0 check (impressions >= 0),
  roi             numeric(8,2) not null default 0,
  activities      jsonb not null default '[]',
  coupons         jsonb not null default '[]',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_campaigns_status  on public.campaigns (status);
create index if not exists idx_campaigns_dates   on public.campaigns (start_date, end_date);

-- Keep updated_at fresh automatically.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_campaigns_updated_at on public.campaigns;
create trigger trg_campaigns_updated_at
  before update on public.campaigns
  for each row execute function public.set_updated_at();


-- ============================================================================
-- 2. CUSTOMERS
-- ============================================================================
-- segment : VIP | Corporate | Retail
-- status  : Active | Pending | Draft | Paused | Completed

create table public.customers (
  id            integer primary key generated by default as identity,
  name          text not null,
  email         text not null,
  phone         text not null default '',
  segment       text not null default 'Retail',
  status        text not null default 'Active',
  last_activity date not null default current_date,
  joined_at     date not null default current_date
);

create index if not exists idx_customers_segment on public.customers (segment);
create index if not exists idx_customers_status  on public.customers (status);
create unique index if not exists uq_customers_email on public.customers (email);


-- ============================================================================
-- 3. LEADS
-- ============================================================================
-- status     : New | Contacted | Qualified | Unqualified | Converted
-- priority   : High | Medium | Low
-- source     : Website | Social Media | Email | Referrals | Paid Ads

create table public.leads (
  id          integer primary key generated by default as identity,
  name        text not null,
  company     text not null default '',
  email       text not null,
  phone       text not null default '',
  source      text not null default 'Website',
  score       integer not null default 0 check (score between 0 and 100),
  assigned_to text not null default '',
  status      text not null default 'New',
  priority    text not null default 'Medium',
  created_at  date not null default current_date
);

create index if not exists idx_leads_status on public.leads (status);
create index if not exists idx_leads_source on public.leads (source);


-- ============================================================================
-- 4. OPPORTUNITIES
-- ============================================================================
-- stage : New | Qualified | Proposal | Negotiation | Won
--         (the dashboard pipeline chart groups by exactly these five)

create table public.opportunities (
  id          integer primary key generated by default as identity,
  name        text not null,
  company     text not null default '',
  value       numeric(14,2) not null default 0 check (value >= 0),
  owner       text not null default '',
  probability integer not null default 0 check (probability between 0 and 100),
  stage       text not null default 'New',
  created_at  date not null default current_date
);

create index if not exists idx_opportunities_stage on public.opportunities (stage);


-- ============================================================================
-- 5. BUDGETS
-- ============================================================================
-- Mirrors lib/models/budget.dart (Budget / BudgetRepository).
-- id     : TEXT ('B001', ...) generated by the Flutter app
-- status : Active | Paused | Completed | Draft

create table public.budgets (
  id          text primary key,
  name        text not null,
  category    text not null default 'Other',
  allocated   numeric(14,2) not null default 0 check (allocated >= 0),
  spent       numeric(14,2) not null default 0 check (spent >= 0),
  start_date  date,
  end_date    date,
  description text not null default '',
  status      text not null default 'Active',
  last_updated date
);

create index if not exists idx_budgets_status on public.budgets (status);


-- ============================================================================
-- 6. PROMOTIONS
-- ============================================================================
-- Mirrors the Promotion model in lib/models/promotion.dart.
-- id            : TEXT ('PR001', ...) generated by the Flutter app
-- type          : Percentage | Fixed Amount | Free Shipping | BOGO
-- status        : Active | Draft | Completed | Paused | Cancelled
-- coupon_codes  : text array of coupon codes

create table public.promotions (
  id             text primary key,
  name           text not null,
  type           text not null default 'Percentage',
  discount       text not null default '',
  discount_value numeric(10,2) not null default 0 check (discount_value >= 0),
  start_date     date not null default current_date,
  end_date       date not null default current_date,
  usage_limit    integer not null default 0 check (usage_limit >= 0),
  used_count     integer not null default 0 check (used_count >= 0),
  status         text not null default 'Active',
  campaign_name  text not null default '',
  coupon_codes   text[] not null default '{}'
);

create index if not exists idx_promotions_status on public.promotions (status);


-- ============================================================================
-- 6b. INFLUENCERS
-- ============================================================================
-- Mirrors the Influencer model in lib/models/influencer.dart.
-- id        : TEXT ('INF001', ...) generated by the Flutter app
-- platform  : Instagram | TikTok | YouTube | Twitter | Facebook | Other
-- status    : Active | Paused | Completed
-- NOTE: avatarColor is derived in-app from the id, so it is not persisted.

create table public.influencers (
  id              text primary key,
  name            text not null,
  handle          text not null default '',
  platform        text not null default 'Instagram',
  followers       integer not null default 0 check (followers >= 0),
  engagement_rate numeric(5,2) not null default 0 check (engagement_rate >= 0),
  category        text not null default 'General',
  status          text not null default 'Active',
  cost_per_post   numeric(12,2) not null default 0 check (cost_per_post >= 0),
  campaign_name   text not null default '',
  avatar_initials text not null default ''
);

create index if not exists idx_influencers_status   on public.influencers (status);
create index if not exists idx_influencers_platform on public.influencers (platform);


-- ============================================================================
-- 6c. CONTENT ITEMS
-- ============================================================================
-- Mirrors the ContentItem model in lib/models/content_item.dart.
-- id     : TEXT ('CN001', ...) generated by the Flutter app
-- type   : Blog Post | Video | Social Post | Email | Infographic | Webinar
-- status : Active (Published) | Paused (Scheduled) | Draft | Completed (Archived)

create table public.content_items (
  id             text primary key,
  title          text not null,
  type           text not null default 'Blog Post',
  channel        text not null default 'Website',
  creator        text not null default '',
  status         text not null default 'Draft',
  scheduled_date date not null default current_date,
  campaign_name  text not null default '',
  description    text not null default '',
  views          integer not null default 0 check (views >= 0),
  clicks         integer not null default 0 check (clicks >= 0)
);

create index if not exists idx_content_items_status on public.content_items (status);
create index if not exists idx_content_items_type   on public.content_items (type);


-- ============================================================================
-- 7. ROW LEVEL SECURITY
-- ============================================================================
-- The Flutter app connects with the publishable/anon key and has no user auth
-- yet, so these policies grant full access during development.
--
-- WARNING: prototyping only. Before production enable Supabase Auth and
-- replace with role-based policies, e.g.
--   create policy "auth read" on public.campaigns
--     for select to authenticated using (true);

alter table public.campaigns      enable row level security;
alter table public.customers      enable row level security;
alter table public.leads          enable row level security;
alter table public.opportunities  enable row level security;
alter table public.budgets        enable row level security;
alter table public.promotions     enable row level security;
alter table public.influencers    enable row level security;
alter table public.content_items  enable row level security;

do $$
declare t text;
begin
  foreach t in array array['campaigns','customers','leads','opportunities','budgets','promotions','influencers','content_items']
  loop
    execute format('drop policy if exists "allow all for anon dev" on public.%I;', t);
    execute format(
      'create policy "allow all for anon dev" on public.%I
         for all to anon, authenticated using (true) with check (true);', t);
  end loop;
end $$;


-- ============================================================================
-- 8. SAMPLE DATA
-- ============================================================================
-- Optional but recommended: matches the samples bundled in the Flutter code,
-- so the database starts out identical to what the app shows offline.
-- (Campaigns would also be auto-seeded by the app on first run if empty.)

insert into public.campaigns
  (id, name, description, target_audience, objective, channels, status,
   start_date, end_date, budget, spent, leads, conversions, impressions, roi,
   activities, coupons)
values
  ('C001', 'Summer Sale 2026',
   'Boost summer product sales with targeted promotions across digital channels.',
   'Online shoppers, 18-45', 'salesConversion', '{socialMedia,email,search}',
   'Active', '2026-05-10', '2026-06-10', 50000, 32450, 320, 85, 45000, 5.2,
   '[{"description":"Campaign launched","date":"May 10, 2026"},{"description":"Social ads went live","date":"May 11, 2026"}]'::jsonb,
   '[{"code":"SUMMER20","discount":"20% off","usageLimit":500,"usedCount":234,"expiryDate":"Jun 10, 2026"}]'::jsonb),

  ('C002', 'Brand Awareness Q2',
   'Increase brand visibility across social platforms.',
   'General consumers, 18-35', 'brandAwareness', '{socialMedia,email}',
   'Active', '2026-04-20', '2026-05-20', 40000, 28300, 210, 45, 38000, 3.8,
   '[{"description":"Campaign brief approved","date":"Apr 20, 2026"}]'::jsonb,
   '[]'::jsonb),

  ('C003', 'Email Nurture May',
   'Nurture leads via email sequences and drip campaigns.',
   'Existing leads, 25-50', 'leadGeneration', '{email}',
   'Completed', '2026-05-01', '2026-05-15', 10000, 7650, 180, 62, 12000, 6.1,
   '[{"description":"Email sequence deployed","date":"May 1, 2026"}]'::jsonb,
   '[]'::jsonb),

  ('C004', 'Product Launch X',
   'Launch of product X with multi-channel advertising.',
   'Tech enthusiasts, 22-40', 'salesConversion', '{search,socialMedia}',
   'Paused', '2026-05-05', '2026-06-05', 60000, 21200, 150, 28, 25000, 2.9,
   '[{"description":"Campaign paused for review","date":"May 12, 2026"}]'::jsonb,
   '[{"code":"LAUNCHX10","discount":"10% off","usageLimit":300,"usedCount":89,"expiryDate":"Jun 5, 2026"}]'::jsonb),

  ('C005', 'Re-engagement May',
   'Win back inactive users with personalized offers.',
   'Inactive users, 25-55', 'customerRetention', '{email,sms}',
   'Active', '2026-05-08', '2026-05-29', 15000, 8900, 95, 38, 8000, 4.7,
   '[{"description":"Re-engagement emails sent","date":"May 8, 2026"}]'::jsonb,
   '[{"code":"COMEBACK15","discount":"15% off","usageLimit":200,"usedCount":67,"expiryDate":"May 29, 2026"}]'::jsonb),

  ('C006', 'Holiday Promo',
   'Holiday season promotion across social and search.',
   'All segments', 'salesConversion', '{socialMedia,search,display}',
   'Draft', null, null, 30000, 0, 0, 0, 0, 0,
   '[]'::jsonb,
   '[]'::jsonb);

insert into public.customers (id, name, email, phone, segment, status, last_activity, joined_at) values
  (1,  'Abebe Kebede',    'abebe.kebede@techwave.com',      '+251 911 234 567', 'VIP',       'Active',    '2026-05-12', '2023-01-10'),
  (2,  'Sara Ahmed',      'sara.ahmed@greenleaf.co',        '+251 922 345 678', 'Corporate', 'Active',    '2026-05-11', '2023-04-22'),
  (3,  'John Smith',      'john.smith@globalretail.com',    '+251 933 456 789', 'Retail',    'Draft',     '2026-04-28', '2022-11-05'),
  (4,  'Meron Tadesse',   'meron.t@innovate.et',            '+251 944 567 890', 'Retail',    'Pending',   '2026-05-10', '2024-02-14'),
  (5,  'Daniel Girma',    'daniel.girma@nexustech.com',     '+251 955 678 901', 'Corporate', 'Active',    '2026-05-09', '2023-08-03'),
  (6,  'Hana Bekele',     'hana.b@brightstar.io',           '+251 966 789 012', 'VIP',       'Active',    '2026-05-08', '2024-01-05'),
  (7,  'Yonas Alemu',     'yonas.a@summitgroup.com',        '+251 977 890 123', 'Corporate', 'Paused',    '2026-04-15', '2023-06-20'),
  (8,  'Lidya Haile',     'lidya.h@freshstart.et',          '+251 988 901 234', 'Retail',    'Active',    '2026-05-12', '2024-03-01'),
  (9,  'Samuel Tesfaye',  'samuel.t@apexventures.com',      '+251 999 012 345', 'VIP',       'Active',    '2026-05-07', '2022-09-18'),
  (10, 'Kenenisa Bekele', 'kenenisa.b@speedlogistics.com',  '+251 910 123 456', 'Corporate', 'Pending',   '2026-05-05', '2024-11-22'),
  (11, 'Rahel Tesfaye',   'rahel.t@bloomdesign.co',         '+251 921 234 567', 'Retail',    'Active',    '2026-05-11', '2023-12-05'),
  (12, 'Bereket Yohannes','bereket.y@corebuild.et',         '+251 932 345 678', 'Corporate', 'Completed', '2026-03-30', '2022-05-14');

insert into public.leads (id, name, company, email, phone, source, score, assigned_to, status, priority, created_at) values
  (1,  'Abebe Kebede',    'TechWave Inc.',    'abebe@techwave.com',       '+251 911 234 567', 'Website',      85, 'Hana Tsegaye',  'Qualified',   'High',   '2026-05-01'),
  (2,  'Sara Ahmed',      'GreenLeaf Co.',    'sara@greenleaf.co',        '+251 922 345 678', 'Social Media', 72, 'Daniel Girma',  'New',         'Medium', '2026-05-03'),
  (3,  'John Smith',      'Global Retail',    'john@globalretail.com',    '+251 933 456 789', 'Email',        45, 'Meron Tadesse', 'Contacted',   'Low',    '2026-05-05'),
  (4,  'Meron Tadesse',   'Innovate ET',      'meron@innovate.et',        '+251 944 567 890', 'Referrals',    91, 'Hana Tsegaye',  'Qualified',   'High',   '2026-05-02'),
  (5,  'Daniel Girma',    'NexusTech',        'daniel@nexustech.com',     '+251 955 678 901', 'Paid Ads',     38, 'Yonas Alemu',   'Unqualified', 'Low',    '2026-05-04'),
  (6,  'Hana Bekele',     'BrightStar IO',    'hana@brightstar.io',       '+251 966 789 012', 'Website',      68, 'Daniel Girma',  'New',         'Medium', '2026-05-06'),
  (7,  'Yonas Alemu',     'Summit Group',     'yonas@summitgroup.com',    '+251 977 890 123', 'Social Media', 55, 'Meron Tadesse', 'Contacted',   'Medium', '2026-05-07'),
  (8,  'Lidya Haile',     'FreshStart ET',    'lidya@freshstart.et',      '+251 988 901 234', 'Referrals',    95, 'Hana Tsegaye',  'Converted',   'High',   '2026-04-28'),
  (9,  'Samuel Tesfaye',  'Apex Ventures',    'samuel@apexventures.com',  '+251 999 012 345', 'Website',      60, 'Yonas Alemu',   'New',         'Medium', '2026-05-08'),
  (10, 'Kenenisa Bekele', 'SpeedLogistics',   'kenenisa@speedlogistics.com','+251 910 123 456','Paid Ads',     78, 'Daniel Girma',  'Qualified',   'High',   '2026-05-09'),
  (11, 'Rahel Tesfaye',   'BloomDesign Co.',  'rahel@bloomdesign.co',     '+251 921 234 567', 'Email',        42, 'Meron Tadesse', 'Contacted',   'Low',    '2026-05-10'),
  (12, 'Bereket Yohannes','CoreBuild ET',     'bereket@corebuild.et',     '+251 932 345 678', 'Website',      88, 'Hana Tsegaye',  'Qualified',   'High',   '2026-05-11');

insert into public.opportunities (id, name, company, value, owner, probability, stage, created_at) values
  (1,  'Summer Campaign Package',  'TechWave Inc.',   45000, 'Hana Tsegaye', 80, 'Proposal',   '2026-04-15'),
  (2,  'Brand Awareness Q3',       'GreenLeaf Co.',   28000, 'Daniel Girma', 60, 'Negotiation','2026-04-20'),
  (3,  'Product Launch Support',   'NexusTech',       65000, 'Yonas Alemu',  40, 'Qualified',  '2026-05-01'),
  (4,  'Email Automation Suite',   'BrightStar IO',   18500, 'Meron Tadesse',90, 'Negotiation','2026-05-03'),
  (5,  'Social Media Takeover',    'Summit Group',    32000, 'Hana Tsegaye', 25, 'New',        '2026-05-08'),
  (6,  'Retargeting Strategy',     'FreshStart ET',   12000, 'Daniel Girma', 70, 'Proposal',   '2026-05-05'),
  (7,  'Influencer Partnership',   'Apex Ventures',   22000, 'Yonas Alemu',  55, 'Qualified',  '2026-05-06'),
  (8,  'Holiday Campaign 2026',    'SpeedLogistics',  52000, 'Hana Tsegaye', 15, 'New',        '2026-05-10'),
  (9,  'SEO Overhaul',             'BloomDesign Co.', 15000, 'Meron Tadesse',95, 'Won',        '2026-04-10'),
  (10, 'PPC Management',           'CoreBuild ET',    28000, 'Daniel Girma', 10, 'New',        '2026-05-12'),
  (11, 'Content Strategy Retainer','TechWave Inc.',   36000, 'Hana Tsegaye', 50, 'Proposal',   '2026-05-02'),
  (12, 'Event Marketing Package',  'GreenLeaf Co.',   18000, 'Yonas Alemu',  30, 'Qualified',  '2026-05-07');

insert into public.budgets
  (id, name, category, allocated, spent, start_date, end_date, description,
   status, last_updated)
values
  ('B001', 'Digital Advertising', 'Advertising', 320000, 272000,
   '2026-01-01', '2026-12-31',
   'Google Ads, Facebook Ads, and display campaigns.', 'Active', '2026-08-10'),
  ('B002', 'Blog & Video Content', 'Content', 150000, 68000,
   '2026-01-01', '2026-12-31',
   'Blog posts, videos, and infographic production.', 'Active', '2026-08-08'),
  ('B003', 'Influencer Partnerships', 'Influencer Marketing', 180000, 178500,
   '2026-04-01', '2026-09-30',
   'Sponsored posts and collaboration fees.', 'Active', '2026-08-12'),
  ('B004', 'Annual Conference', 'Events', 220000, 238000,
   '2026-06-01', '2026-08-31',
   'Addis Ababa marketing summit - venue, catering, AV.', 'Active', '2026-08-14'),
  ('B005', 'Email & SMS Campaigns', 'Email/SMS', 80000, 42000,
   '2026-01-01', '2026-12-31',
   'Bulk email platform, SMS gateway, automation tools.', 'Active', '2026-08-07'),
  ('B006', 'Market Research', 'Other', 50000, 12500,
   '2026-01-01', '2026-06-30',
   'Consumer surveys, competitor analysis, reports.', 'Paused', '2026-07-15');

insert into public.promotions
  (id, name, type, discount, discount_value, start_date, end_date,
   usage_limit, used_count, status, campaign_name, coupon_codes)
values
  ('PR001', 'Summer Flash Sale', 'Percentage', '30% off', 30,
   '2026-05-10', '2026-06-30', 1000, 512, 'Active', 'Summer Sale Promo',
   '{SUMMER30,FLASH30}'),
  ('PR002', 'Launch Day Offer', 'Percentage', '20% off', 20,
   '2026-05-01', '2026-05-31', 500, 342, 'Active', 'Product Launch 2026',
   '{LAUNCH20}'),
  ('PR003', 'Early Bird Discount', 'Percentage', '15% off', 15,
   '2026-05-01', '2026-05-15', 200, 198, 'Completed', 'Product Launch 2026',
   '{EARLY15}'),
  ('PR004', 'Win-Back Offer', 'Percentage', '10% off', 10,
   '2026-04-01', '2026-04-30', 300, 74, 'Paused', 'Re-engagement Campaign',
   '{COMEBACK10}'),
  ('PR005', 'Loyalty Reward', 'Fixed Amount', 'ETB 500 off', 500,
   '2026-06-01', '2026-08-31', 150, 0, 'Draft', 'Brand Awareness Q3',
   '{LOYAL500}'),
  ('PR006', 'Referral Bonus', 'Percentage', '25% off', 25,
   '2026-05-15', '2026-07-15', 400, 128, 'Active', 'Lead Gen — SME',
   '{REFER25,REF25B}');

insert into public.influencers
  (id, name, handle, platform, followers, engagement_rate, category,
   status, cost_per_post, campaign_name, avatar_initials)
values
  ('INF001', 'Abel Tafesse', '@abeltafesse', 'Instagram', 245000, 5.80,
   'Tech', 'Active', 12000, 'Product Launch 2026', 'AT'),
  ('INF002', 'Tizita Habte', '@tizitah', 'TikTok', 890000, 8.20,
   'Lifestyle', 'Active', 28000, 'Summer Sale Promo', 'TH'),
  ('INF003', 'Kidus Mamo', '@kidusmamo', 'YouTube', 120000, 4.10,
   'Gaming', 'Paused', 8500, 'Brand Awareness Q3', 'KM'),
  ('INF004', 'Mekdes Alemu', '@mekdesalemu', 'Instagram', 310000, 6.50,
   'Fashion', 'Active', 16000, 'Influencer Collab Q2', 'MA'),
  ('INF005', 'Yonas Getachew', '@yonasgetachew', 'Twitter', 78000, 3.40,
   'Business', 'Completed', 5500, 'Lead Gen — SME', 'YG'),
  ('INF006', 'Feven Tadesse', '@feventadesse', 'TikTok', 1200000, 9.10,
   'Beauty', 'Active', 45000, 'Product Launch 2026', 'FT');

insert into public.content_items
  (id, title, type, channel, creator, status, scheduled_date,
   campaign_name, description, views, clicks)
values
  ('CN001', 'How to Boost Your Marketing ROI in 2026', 'Blog Post', 'Website',
   'Sara M.', 'Active', '2026-05-10', 'Brand Awareness Q3',
   'Comprehensive guide on modern marketing ROI tactics.', 3240, 412),
  ('CN002', 'Product Launch Announcement Video', 'Video', 'YouTube',
   'Yonas B.', 'Active', '2026-05-01', 'Product Launch 2026',
   'Official product launch video for the mobile app.', 18500, 2100),
  ('CN003', 'Summer Sale Instagram Carousel', 'Social Post', 'Instagram',
   'Dawit A.', 'Draft', '2026-05-15', 'Summer Sale Promo',
   '5-slide carousel showcasing summer discounts.', 0, 0),
  ('CN004', 'Newsletter #12 — May 2026', 'Email', 'Email',
   'Sara M.', 'Active', '2026-05-08', 'Re-engagement Campaign',
   'Monthly newsletter with product updates and tips.', 9800, 1540),
  ('CN005', 'SME Marketing Guide Infographic', 'Infographic', 'LinkedIn',
   'Yonas B.', 'Completed', '2026-04-20', 'Lead Gen — SME',
   'Visual guide to SME marketing best practices.', 5600, 890),
  ('CN006', 'Live Webinar: Digital Marketing Trends', 'Webinar', 'Zoom',
   'Dawit A.', 'Paused', '2026-06-05', 'Brand Awareness Q3',
   'Monthly webinar exploring current digital trends.', 0, 320),
  ('CN007', 'TikTok Brand Story', 'Video', 'TikTok',
   'Sara M.', 'Active', '2026-05-12', 'Influencer Collab Q2',
   'Short-form brand storytelling video for TikTok.', 42000, 3800);


-- ============================================================================
-- 9. FIX IDENTITY SEQUENCES AFTER EXPLICIT-ID SEEDING
-- ============================================================================

select setval(pg_get_serial_sequence('public.customers', 'id'),
              coalesce((select max(id) from public.customers), 1));
select setval(pg_get_serial_sequence('public.leads', 'id'),
              coalesce((select max(id) from public.leads), 1));
select setval(pg_get_serial_sequence('public.opportunities', 'id'),
              coalesce((select max(id) from public.opportunities), 1));


-- ============================================================================
-- 10. VERIFY
-- ============================================================================
-- Expected output: one row per table with its row count.

select 'campaigns'      as table_name, count(*) from public.campaigns
union all select 'customers',     count(*) from public.customers
union all select 'leads',         count(*) from public.leads
union all select 'opportunities', count(*) from public.opportunities
union all select 'budgets',       count(*) from public.budgets
union all select 'promotions',    count(*) from public.promotions
union all select 'influencers',   count(*) from public.influencers
union all select 'content_items', count(*) from public.content_items;
